-- SPK domain: categories, criteria, weight profiles (+ weights), toys (+ tags, scores).
-- Portable DDL (H2 v2 PostgreSQL mode + PostgreSQL). Matches the JPA entities.

CREATE TABLE categories (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50)  NOT NULL UNIQUE,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(512),
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE criteria (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50)  NOT NULL UNIQUE,
    no          INTEGER      NOT NULL,
    name        VARCHAR(255) NOT NULL,
    type        VARCHAR(20)  NOT NULL,
    description VARCHAR(512),
    abbr        VARCHAR(50),
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE weight_profiles (
    id          BIGINT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50)      NOT NULL UNIQUE,
    name        VARCHAR(255)     NOT NULL,
    short_name  VARCHAR(50),
    icon        VARCHAR(30),
    description VARCHAR(512),
    is_default  BOOLEAN          NOT NULL DEFAULT FALSE,
    active      BOOLEAN          NOT NULL DEFAULT TRUE,
    cr          DOUBLE PRECISION NOT NULL DEFAULT 0,
    lambda_max  DOUBLE PRECISION NOT NULL DEFAULT 0,
    ci          DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at  TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE weight_profile_weights (
    weight_profile_id BIGINT           NOT NULL REFERENCES weight_profiles(id) ON DELETE CASCADE,
    criterion_code    VARCHAR(50)      NOT NULL,
    weight            DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (weight_profile_id, criterion_code)
);

CREATE TABLE toys (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    category_code VARCHAR(50)  NOT NULL,
    price         BIGINT       NOT NULL,
    age_min       INTEGER      NOT NULL,
    age_max       INTEGER      NOT NULL,
    stock         INTEGER      NOT NULL,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    description   VARCHAR(512),
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE toy_tags (
    toy_id BIGINT       NOT NULL REFERENCES toys(id) ON DELETE CASCADE,
    tag    VARCHAR(100) NOT NULL
);

CREATE TABLE toy_scores (
    toy_id         BIGINT      NOT NULL REFERENCES toys(id) ON DELETE CASCADE,
    criterion_code VARCHAR(50) NOT NULL,
    rating         INTEGER     NOT NULL,
    PRIMARY KEY (toy_id, criterion_code)
);

CREATE INDEX idx_toys_category_code ON toys(category_code);
