-- Calculation sessions: per-run, per-profile rankings (snapshot for reports/publish).

CREATE TABLE calculation_runs (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(20) NOT NULL UNIQUE,
    run_at       TIMESTAMP   NOT NULL,
    alt_count    INTEGER     NOT NULL,
    published    BOOLEAN     NOT NULL DEFAULT FALSE,
    published_at TIMESTAMP,
    created_at   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE calculation_results (
    id            BIGINT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id        BIGINT           NOT NULL REFERENCES calculation_runs(id) ON DELETE CASCADE,
    profile_code  VARCHAR(50)      NOT NULL,
    profile_name  VARCHAR(255)     NOT NULL,
    cr            DOUBLE PRECISION NOT NULL,
    lambda_max    DOUBLE PRECISION NOT NULL,
    ci            DOUBLE PRECISION NOT NULL,
    consistent    BOOLEAN          NOT NULL,
    best_toy_id   INTEGER,
    best_toy_name VARCHAR(255),
    created_at    TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ranking_entries (
    id            BIGINT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    result_id     BIGINT           NOT NULL REFERENCES calculation_results(id) ON DELETE CASCADE,
    toy_id        INTEGER          NOT NULL,
    toy_name      VARCHAR(255)     NOT NULL,
    category_name VARCHAR(255),
    rank_no       INTEGER          NOT NULL,
    saw_score     DOUBLE PRECISION NOT NULL,
    created_at    TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_calc_results_run ON calculation_results(run_id);
CREATE INDEX idx_ranking_entries_result ON ranking_entries(result_id);
