-- Frozen decision snapshot per calculation run (the publish gate source of truth).
-- Public API reads scores/ranking/weights/r_ij from the latest PUBLISHED run; toy display
-- attributes are hydrated live per toy_id.

ALTER TABLE calculation_results ADD COLUMN short_name VARCHAR(255);
ALTER TABLE calculation_results ADD COLUMN icon VARCHAR(50);

-- Frozen criteria set (type drives normalization; name/abbr for labels; no for ordering).
CREATE TABLE calculation_criteria (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id         BIGINT       NOT NULL REFERENCES calculation_runs(id) ON DELETE CASCADE,
    criterion_code VARCHAR(50)  NOT NULL,
    name           VARCHAR(255) NOT NULL,
    abbr           VARCHAR(50),
    type           VARCHAR(20)  NOT NULL,
    no             INT          NOT NULL,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_calc_criteria UNIQUE (run_id, criterion_code)
);

-- Frozen AHP weight per profile result per criterion.
CREATE TABLE calculation_weights (
    id             BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    result_id      BIGINT      NOT NULL REFERENCES calculation_results(id) ON DELETE CASCADE,
    criterion_code VARCHAR(50) NOT NULL,
    weight         DOUBLE PRECISION NOT NULL,
    created_at     TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_calc_weights UNIQUE (result_id, criterion_code)
);

-- Frozen normalized value r_ij per toy per criterion (0..1).
CREATE TABLE calculation_norms (
    id             BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id         BIGINT      NOT NULL REFERENCES calculation_runs(id) ON DELETE CASCADE,
    toy_id         INT         NOT NULL,
    criterion_code VARCHAR(50) NOT NULL,
    norm_value     DOUBLE PRECISION NOT NULL,
    created_at     TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_calc_norms UNIQUE (run_id, toy_id, criterion_code)
);

CREATE INDEX idx_calc_criteria_run ON calculation_criteria(run_id);
CREATE INDEX idx_calc_weights_result ON calculation_weights(result_id);
CREATE INDEX idx_calc_norms_run ON calculation_norms(run_id);
