-- Subcriteria (S1–S5) per criterion, with the AHP local priority each band carries.
-- These replace the min/max normalization the synthesis used to do: an alternative's
-- value on a criterion is now the priority of the band it falls into, so the method
-- is plain AHP end to end.

CREATE TABLE criterion_levels (
    id             BIGINT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    criterion_code VARCHAR(50)      NOT NULL,
    level          INTEGER          NOT NULL,
    label          VARCHAR(255)     NOT NULL,
    priority       DOUBLE PRECISION NOT NULL,
    created_at     TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_criterion_levels UNIQUE (criterion_code, level)
);

-- The weight profiles are re-seeded so the default one carries the thesis criteria
-- weights (Tabel 4.6) instead of the old round numbers.
DELETE FROM weight_profile_weights;
DELETE FROM weight_profiles;

-- Every stored ranking came out of the old normalization, so none of them describe
-- the current method. DomainSeeder recomputes and republishes one on next startup.
DELETE FROM calculation_norms;
DELETE FROM calculation_weights;
DELETE FROM calculation_criteria;
DELETE FROM ranking_entries;
DELETE FROM calculation_results;
DELETE FROM calculation_runs;

-- V5 left the toy ids running from 51 because the identity sequence carried on past
-- the catalog it replaced, so "A" + id no longer matched the thesis codes A1–A50.
-- Reseed from 1 (DomainSeeder repopulates the same 50 alternatives in the same order).
DELETE FROM toy_scores;
DELETE FROM toy_tags;
DELETE FROM toys;
ALTER TABLE toys ALTER COLUMN id RESTART WITH 1;
